backend:
  name: git-gateway
  repo: hoangthuaduy/htd-blog
  branch: main

media_folder: "assets/images/uploads"
public_folder: "assets/images/public"

collections:
  - name: "blog"
    label: "Blog Posts"
    folder: "js/blog-posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}
